[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { workspace = true }
utime = "0.3.3"
uuid = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }