CREATE TABLE IF NOT EXISTS referrals(
	referrer UUID NOT NULL,
	referral UUID NOT NULL,
    invited_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
	FOREIGN KEY (referrer) REFERENCES users(id)
		ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (referral) REFERENCES users(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);

ALTER TABLE referrals
ADD CONSTRAINT unique_referral_pair UNIQUE (referrer, referral);

CREATE TABLE IF NOT EXISTS referral_codes(
	referrer UUID NOT NULL UNIQUE,
	code VARCHAR(8) NOT NULL UNIQUE,
	FOREIGN KEY (referrer) REFERENCES users(id)
		ON UPDATE CASCADE ON DELETE CASCADE
);